apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  labels:
    app: dummy
spec:
  containers:
    - name: dummy-container
      image: {{ .Values.image.repository}}:latest
      ports:
        - containerPort: 80
