{{- if .Values.subchartEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-subchart-deploy
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-subchart-pod
      app.kubernetes.io/instance : {{ .Release.Name }}
      component : nginx-subchart
  template :
    metadata :
      labels :
        app.kubernetes.io/name : nginx-subchart-pod
        app.kubernetes.io/instance : {{ .Release.Name }}
        component : nginx-subchart
    spec :
      containers :
        - name : nginx-container
          imagePullPolicy : IfNotPresent
{{/*            image : "{{ default (printf \"%s:%s\" $.Values.global.image.repository $.Values.global.image.tag) \"nginx\" }}"*/}}
          image: {{ .Values.global.image.repository }}
{{ end }}
